apache/incubator-hawq-docs

- clientaccess/g-database-application-interfaces.html.md.erb
- clientaccess/g-supported-client-applications.html.md.erb
- hawq-book/master_middleman/source/subnavs/apache-hawq-nav.erb
updates to clarify database application interfaces.  fixes HAWQ-1019
> misc doc updates clarifying APIs

- admin/HAWQFilespacesandHighAvailabilityEnabledHDFS.html.md.erb
- clientaccess/client_auth.html.md.erb
- clientaccess/disable-kerberos.html.md.erb
- clientaccess/kerberos.html.md.erb
- reference/HAWQEnvironmentVariables.html.md.erb
- reference/cli/admin_utilities/gplogfilter.html.md.erb
doc updates to remove references to MASTER_DATA_DIRECTORY.  clarify when the hawq-site.xml hawq_master_directory config value should be used.
should resolve HAWQ-1031
> MASTER_DATA_DIRECTORY clarifications - HAWQ-1031

- master_middleman/source/subnavs/apache-hawq-nav.erb
include gp_vmem_idle_resource_timeout guc in subnav.
> add subnav for gp_vmem_idle_resource_timeout

- install/aws-config.html.md.erb
- pxf/HawqExtensionFrameworkPXF.html.md.erb
- reference/HAWQDataTypes.html.md.erb
- requirements/system-requirements.html.md.erb
- add reverse DNS requirement
- clean up AWS config page
- clarify predefined vs. internal data types
- add JSON plug-in content and link to PXF overview
> miscellaneous doc updates and clarifications

- reference/sql/ALTER-RESOURCE-QUEUE.html.md.erb
- reference/sql/CREATE-RESOURCE-QUEUE.html.md.erb
fix create and alter resource queue documentation per comment on hawq user list.
> VSEGMENT_RESOURCE_QUOTA to VSEG_RESOURCE_QUOTA

- admin/ClusterExpansion.html.md.erb
- admin/ambari-admin.html.md.erb
- clientaccess/disable-kerberos.html.md.erb
- datamgmt/load/client-loadtools.html.md.erb
- pxf/JsonPXF.html.md.erb
- reference/catalog/gp_configuration_history.html.md.erb
- json plugin - use <> for optional params, include link to CREATE EXTERNAL TABLE ref page
- client loading tools - direct to correct download site for windows
- cluster expansion - if using YARN, config a NodeManager on new node
> misc doc updates

- master_middleman/source/subnavs/apache-hawq-nav.erb
> HAWQ-1095 - change database apis subnav title

- master_middleman/source/subnavs/apache-hawq-nav.erb
> HAWQ-1096 - add subnav entry for built-in languages

- clientaccess/g-database-application-interfaces.html.md.erb
add content for jdbc, odbc, libpq
> HAWQ-1095 - enhance database api docs

- datamgmt/load/client-loadtools.html.md.erb
update client loader tools section to include install instructions for dependent libraries libevent and libyaml.
> add gpfdist library dependencies

- master_middleman/source/subnavs/apache-hawq-nav.erb
> HAWQ-1107 - subnav chgs for pxf hdfs plugin content restructure

- master_middleman/source/subnavs/apache-hawq-nav.erb
> HAWQ-1107 - more subnav changes for HDFS plugin

- master_middleman/source/subnavs/apache-hawq-nav.erb
removed all submenus from the subnav
> HAWQ-1071 - subnav changes for pxf enhancement work

- pxf/HivePXF.html.md.erb
added examples, restructured content, added hive command line section.
> HAWQ-1071 - add examples for HiveText and HiveRC plugins

- pxf/HDFSFileDataPXF.html.md.erb
incorporated kavinder's comments on HDFS plug in doc restructure.
> HAWQ-1107 - incorporate kavinder's comments

- master_middleman/source/subnavs/apache-hawq-nav.erb
- move PXF topic to first level
- change names of PXF and Managing Data topics
- remove submenus from all PXF subtopics
> subnav changes for PXF

- admin/BackingUpandRestoringHAWQDatabases.html.md.erb
- admin/ClusterExpansion.html.md.erb
- admin/HAWQFilespacesandHighAvailabilityEnabledHDFS.html.md.erb
- admin/monitor.html.md.erb
- bestpractices/managing_data_bestpractices.html.md.erb
- bestpractices/querying_data_bestpractices.html.md.erb
- clientaccess/kerberos.html.md.erb
- clientaccess/roles_privs.html.md.erb
- datamgmt/HAWQInputFormatforMapReduce.html.md.erb
- datamgmt/load/g-loading-data-using-an-external-table.html.md.erb
- datamgmt/load/g-register_files.html.md.erb
- ddl/ddl-database.html.md.erb
- ddl/ddl-tablespace.html.md.erb
- plext/builtin_langs.html.md.erb
- plext/using_pljava.html.md.erb
- plext/using_plpython.html.md.erb
- plext/using_plr.html.md.erb
- pxf/HDFSFileDataPXF.html.md.erb
- pxf/HivePXF.html.md.erb
- pxf/TroubleshootingPXF.html.md.erb
- query/gporca/query-gporca-enable.html.md.erb
- query/gporca/query-gporca-fallback.html.md.erb
- query/gporca/query-gporca-features.html.md.erb
- query/query-performance.html.md.erb
- query/query-profiling.html.md.erb
- resourcemgmt/ConfigureResourceManagement.html.md.erb
- resourcemgmt/ResourceManagerStatus.html.md.erb
- resourcemgmt/ResourceQueues.html.md.erb
- count rows in table, not db
- code block formatting issue
- SQL commands should be all caps - for all content except HAWQ Reference section
> bundle up miscellaneous updates

- admin/MasterMirroring.html.md.erb
edited the existing content and added info and links for ambari procedures related to the master standby.
> HAWQ-1142 - add ambari procedures to master mirroring docs section

- admin/startstop.html.md.erb
- clientaccess/client_auth.html.md.erb
- datamgmt/load/client-loadtools.html.md.erb
- query/gporca/query-gporca-enable.html.md.erb
- reference/cli/admin_utilities/hawqconfig.html.md.erb
- reference/guc/parameter_definitions.html.md.erb
updated appropriate files to include cluster <object> in hawq stop -u commands.
> HAWQ-1146 - ensure all hawq stop -u references include <object>

- master_middleman/source/subnavs/apache-hawq-nav.erb
Removing nav for catch-all generalbestpractices section.
> Remove general bestpractices subnav
